spring:
  application:
    name: activity-service
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://mongodb:27017/fitnessactivity}
      database: ${SPRING_DATA_MONGODB_DATABASE:fitnessactivity}
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:rabbitmq}
    port: 5672
    username: ${SPRING_RABBITMQ_USERNAME}
    password: ${SPRING_RABBITMQ_PASSWORD}

server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/

rabbitmq:
  exchange:
    name: fitness.exchange
  queue:
    name: activity.queue
  routing:
    key: activity.tracking