server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/fitness_user_db
    username: postgres
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/

keycloak:
  auth-server-url: ${KEYCLOAK_AUTH_SERVER_URL:http://keycloak:8080/auth}
  realm: ${KEYCLOAK_REALM:fitness-oauth2}
  admin:
    client-id: ${KEYCLOAK_ADMIN_CLIENT_ID:admin-cli}
    client-secret: ${KEYCLOAK_ADMIN_CLIENT_SECRET}
  default-role: ROLE_USER